addd new pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,75 +1,231 @@
-name: VISIT WITH US TOURISM PREDICTION PIPELINE
+name: Visit With Us Toursim Prediction Pipeline
+
 on:
   push:
     branches:
-      - main
+      - main # Automatically triggers on push to the main branch
     paths:
-      - 'Master/Deployment/**'
       - 'Master/Data/tourism.csv'
-      - 'Master/main.py'
       - 'Master/DataRegistration.py'
       - 'Master/DataPrepration.py'
-      - 'Master/ModelBuilding.py'
+      - 'Master/BuildingModels.py'
+      - 'Master/main.py'
       - 'Master/HostingInHuggingFace.py'
       - '.github/workflows/pipeline.yml'
+      - 'Master/Deployment/**'
   workflow_dispatch:
 
 jobs:
-  data_registration:
+  register-dataset:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/checkout@v3
+      
+      - name: Setup python
+        uses: actions/setup-python@v5
         with:
           python-version: '3.12'
-
+      
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install huggingface_hub python-dotenv pandas
-
-      - name: List Direcory contents(debug)
+          pip install huggingface_hub python-dotenv
+      
+      - name: List Directory Contents(Debug)
         run: |
-          ls -la . || echo "Root Directory Contents"
-          ls -la Master/Data/ || echo "Master/Data/ Directory not found"
-          ls -la Master/ || echo "Master Directory"
+          ls -la Master/Data/ || echo "Master/Data/ directory not found"
+          ls -la . || echo "Root Directory contents"
 
-      - name: Copy Dataset File
+      - name: Copy tourism.csv(if using a local file)
+        run: |
+          mkdir -p Master/Data 
+          if [ -f tourism.csv ]; then
+            cp tourism.csv Master/Data/
+            echo "Copied tourism.csv from root to Master/Data/"
+          else
+            echo "tourism.csv not found in root attemtpting to download from hugging face"
+
+            python -c "from huggingface_hub import hf_hub_download;hf_hub_download(repo_id='jpkarthikeyan/Tourism-visit-with-us-dataset',filename='tourism.csv',local_dir='Master/Data/')"
+            fi
+      
+      - name: Run Data Registration
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: |
-          mkdir -p Master/Data
-          if [ -f Master/Data/tourism.csv ]; then
-            echo "tourism.csv found in Master/Data"
-          else
-            echo "tourism.csv not found in Master/Data/"
-          fi
+          cd Master
+          python main.py --job register
+        continue-on-error: false
 
-      - name: Run DataRegistration.py
-        env:
-          HF_TOKEN: ${{ secrets.HF_TOKEN}}
-        run: |
-          if [ -d Master ]; then
-            cd Master/
-            python main.py --job register
-          else
-            echo "Master Directory not found"
-            exit 1
-          fi
-          
-
-      - name: Check Pipeline Status
+      - name: Check Pipeline status
         if: failure()
         run: |
-          echo "DataRegistration pipeline failed. please check logs"
+          echo "Data Registration pipeline failed. please check logs"
           exit 1
-
+      
       - name: Verify Upload
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: |
           echo "Verifying Upload on Hugging Face"
-          python -c "import os; from huggingface_hub import HfApi; api=HfApi(token=os.getenv('HF_TOKEN'));print(api.repo_info(repo_id='jpkarthikeyan/Tourism-Visit-With-us-dataset',repo_type='dataset))"
+          python -c "import os;from huggingface_hub import HfApi;api= HfApi(token=os.getenv('HF_TOKEN'));print(api.repo_info(repo_id='jpkarthikeyan/Tourism-visit-with-us-dataset',repo_type='dataset'))"
+
+  data-prepration:
+    runs-on: ubuntu-latest
+    needs: register-dataset
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas numpy huggingface_hub python-dotenv datasets scikit-learn
+
+      - name: Copying tourism.csv
+        run: |
+          mkdir -p Master/Data
+          cp tourism.csv Master/Data || echo "tourism.csv not found in root"
+
+      - name: Run DataPrepration.py
+        env:
+          HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        run: |
+          cd Master
+          python main.py --job prepare
+        continue-on-error: false
+
+      - name: Check Pipeline Status
+        if: failure()
+        run: |
+          echo "Data Prepration pipeline failed. please check the log"
+          exit 1
+      - name: Verify Upload
+        env:
+          HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        run: |
+          echo "Verifying Upload on Hugging Face"
+          python -c "import os; from huggingface_hub import HfApi; token = os.getenv('HF_TOKEN');print(HfApi(token=token).repo_info(repo_id='jpkarthikeyan/Tourism-visit-with-us-dataset', repo_type='dataset'))"
+
+  model-building:
+    runs-on: ubuntu-latest
+    needs: data-prepration
+    steps: 
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+      
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12' 
+      
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install huggingface_hub python-dotenv pandas numpy scikit-learn joblib xgboost seaborn matplotlib datasets
+
+      - name: Create Model Dump Directory
+        run: |
+          mkdir -p Master/Model_Dump_JOBLIB
+
+      - name: Run Model Building
+        env:
+          HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        run: |
+          cd Master
+          python main.py --job modelbuilding
+        continue-on-error: false
+      
+      - name: Check pipeline status
+        if: failure()
+        run: |
+          echo "Exception in Build Models. please check logs"
+          exist 1
+      
+      - name: Verify Execution
+        env:
+          HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        run: |
+          echo "Verifying the execution"
+          python -c "import os; from huggingface_hub import HfApi;token=os.getenv('HF_TOKEN');print(HfApi(token=token).repo_info(repo_id='jpkarthikeyan/Tourism_Prediction_Model',repo_type='model')) "
+
+      - name: List Generated Files
+        run: |
+          ls -l Master/Model_Dump_JOBLIB/
+
+      
+      
+      - name: Commit and Push Generated Files
+        
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions@users.noreply.github.com'
+          git add Master/Model_Dump_JOBLIB/*
+          git commit -m "Adding genearated model files and confusion matrix plots" || echo "No changes to commit"
+          
+      - name: Pull Remote changes
+        run: |
+          git pull origin main --rebase
+      
+      - name: Push Generated Files
+        run: |
+          git pull origin main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  deploy-to-spaces:
+    runs-on: ubuntu-latest
+    needs: model-building
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: SET UP PYTHON
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      
+      - name: INSTALL DEPENDENCIES
+        run: |
+          python -m pip install --upgrade pip
+          pip install huggingface_hub python-dotenv
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to GITHUB CONTAINER REGISTRY
+        env:
+          HF_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo $HF_TOKEN | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
+      
+      - name: Build and Push Docker image to GITHUB Container REGISTRY
+        env:
+          HF_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          cd Master/Deployment
+          docker build -t jpkarthik/tourism-prediction-app:latest .
+          docker tag jpkarthik/tourism-prediction-app:latest ghcr.io/jpkarthik/tourism-prediction-app:latest
+          docker push ghcr.io/jpkarthik/tourism-prediction-app:latest
+        
+      - name: Deploy to Hugging Face Spaces
+        env:
+          HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        run: |
+          cd Master
+          python main.py --job deploy
+          echo "Deployment To HF Space"
+          
+
+      - name: Check Deployment Status
+        if: failure()
+        run: |
+          echo "Deployment to Huggingface space failed please check logs"
+          exit 1
